site_name: Apuntes 1º Programación DAM
repo_url: https://github.com/mmourazos/DAM_PR_Apuntes

theme:
  name: material
  language: es
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmourazos/DAM_PR_Apuntes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      


